# Generated by Django 6.0.3 on 2026-04-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='appointment_info',
        ),
    ]
