# Generated by Django 6.0.3 on 2026-04-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_reminder_appointment_info'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment'),
            preserve_default=False,
        ),
    ]
